# docker-compose.yml
version: "3.9"
services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  importer:
    build: .
    env_file:
      - .env
    command: bash -c "python src/import_to_postgres.py --data-dir src/data/raw"
    depends_on:
      - postgres

volumes:
  pg_data:
